import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const START_MARKER = '<!-- memory-search-context:start -->';
const END_MARKER = '<!-- memory-search-context:end -->';

export function generateContextBlock(memories: Array<{ file: string; snippet: string; score: number }>): string {
  if (memories.length === 0) return '';

  const lines = [
    START_MARKER,
    '',
    '## Memory Search Context',
    '',
    '> Auto-generated by `memory context sync`. Do not edit between markers.',
    '',
  ];

  for (const mem of memories) {
    lines.push(`### ${mem.file} (${Math.round(mem.score * 100)}%)`);
    lines.push('');
    lines.push(mem.snippet);
    lines.push('');
  }

  lines.push(END_MARKER);
  return lines.join('\n');
}

export function upsertClaudeMd(projectPath: string, contextBlock: string): string {
  const claudeMdPath = join(projectPath, 'CLAUDE.md');

  let content = '';
  if (existsSync(claudeMdPath)) {
    content = readFileSync(claudeMdPath, 'utf-8');
  }

  // Check if markers exist
  const startIdx = content.indexOf(START_MARKER);
  const endIdx = content.indexOf(END_MARKER);

  if (startIdx !== -1 && endIdx !== -1) {
    // Replace existing block
    content = content.slice(0, startIdx) + contextBlock + content.slice(endIdx + END_MARKER.length);
  } else {
    // Append new block
    if (content.length > 0 && !content.endsWith('\n')) {
      content += '\n';
    }
    content += '\n' + contextBlock + '\n';
  }

  writeFileSync(claudeMdPath, content);
  return claudeMdPath;
}

export function removeContextBlock(projectPath: string): boolean {
  const claudeMdPath = join(projectPath, 'CLAUDE.md');
  if (!existsSync(claudeMdPath)) return false;

  let content = readFileSync(claudeMdPath, 'utf-8');
  const startIdx = content.indexOf(START_MARKER);
  const endIdx = content.indexOf(END_MARKER);

  if (startIdx === -1 || endIdx === -1) return false;

  // Remove the block including surrounding whitespace
  const before = content.slice(0, startIdx).replace(/\n+$/, '\n');
  const after = content.slice(endIdx + END_MARKER.length).replace(/^\n+/, '\n');
  content = before + after;

  writeFileSync(claudeMdPath, content.trim() + '\n');
  return true;
}
